---

- name: network-config
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
  roles:
    - role: common-network
    - role: hostapd
    - role: dnsmasq
    - role: iptables
  
  tasks:
    - name: Message to reboot
      debug:
        msg: "Config and installation complete, please reboot."

